//Check exceptions

proc bad_calc(err: int -> void)
{
  // do some work, detect an error
  err 1; // throw exception
}

proc main
{
  proc err(errno:int)
  {
    print "error "; print errno;
    print " -- aborting"; endl;
    goto resume;
  }
  bad_calc err of (int);
  print "no error"; endl;
resume:>
  print "error handled, continuing"; endl;
}
main;
